# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170615_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='termregistration',
            name='Sponsor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-07-14'),
        ),
    ]
