# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170714_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='termregistration',
            name='FeesOffer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='termregistration',
            name='TermPayableFees',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TermPayableFees'),
        ),
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-08-01'),
        ),
    ]
