# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170808_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termpayablefees',
            name='Session',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Session'),
        ),
    ]
