# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170808_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-08-09'),
        ),
        migrations.AlterField(
            model_name='termclassadditionalfees',
            name='Is_Boarding',
            field=models.BooleanField(default=False),
        ),
    ]
