# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170809_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceforwarded',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-08-11'),
        ),
    ]
