# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170811_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termregistration',
            old_name='FeesOffer',
            new_name='Fees_offer',
        ),
        migrations.AddField(
            model_name='termregistration',
            name='Student_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-08-12'),
        ),
    ]
