# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170812_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Computer',
        ),
        migrations.AlterField(
            model_name='sponsorreceipt',
            name='Receipt_date',
            field=models.DateField(default=b'2017-08-13'),
        ),
    ]
